//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int idAgenda { get; set; }
        public int mes { get; set; }
        public int año { get; set; }
        public int idEmpresa { get; set; }
        public int idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
