//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaXParametroAgenda
    {
        public int id_param_agenda { get; set; }
        public int id_dia { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_receso { get; set; }
        public Nullable<System.TimeSpan> hora_fin_receso { get; set; }
    
        public virtual DiaSemana DiaSemana { get; set; }
        public virtual ParametroAgenda ParametroAgenda { get; set; }
    }
}
