//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public int idDomicilio { get; set; }
        public string calle { get; set; }
        public int altura { get; set; }
        public Nullable<int> piso { get; set; }
        public string departamento { get; set; }
        public string torre { get; set; }
        public Nullable<int> latitud { get; set; }
        public Nullable<int> longitud { get; set; }
        public Nullable<int> idBarrio { get; set; }
    
        public virtual Barrio Barrio { get; set; }
    }
}
