//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilio()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int idDomicilio { get; set; }
        public string calle { get; set; }
        public int altura { get; set; }
        public Nullable<int> piso { get; set; }
        public string departamento { get; set; }
        public string torre { get; set; }
        public Nullable<int> latitud { get; set; }
        public Nullable<int> longitud { get; set; }
        public Nullable<int> idBarrio { get; set; }
    
        public virtual Barrio Barrio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
