//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int idEmpresa { get; set; }
        public Nullable<decimal> cuit { get; set; }
        public string razonSocial { get; set; }
        public string nombreFantasia { get; set; }
        public Nullable<System.DateTime> inicioActividades { get; set; }
        public string telefono { get; set; }
        public byte[] logoEmpresa { get; set; }
        public string email { get; set; }
        public Nullable<int> idDomicilio { get; set; }
        public Nullable<int> idRubro { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> fechaRegistroEmpresa { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
