//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroAgenda
    {
        public int id_param_agenda { get; set; }
        public int duracion_turno { get; set; }
        public int id_empresa { get; set; }
        public Nullable<bool> atiende_feriado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
