//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaInformeEmpresaFiltros
    {
        public decimal cuit { get; set; }
        public string razonSocial { get; set; }
        public Nullable<System.DateTime> fechaRegistroEmpresa { get; set; }
        public byte[] logoEmpresa { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string calle { get; set; }
        public int altura { get; set; }
        public int idCiudad { get; set; }
        public int idProvincia { get; set; }
        public Nullable<int> idRubro { get; set; }
    }
}
