//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaComentariosAEmpresa
    {
        public int id_empresa { get; set; }
        public int Id_comentario { get; set; }
        public decimal nro { get; set; }
        public int id_cliente { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha_comentario { get; set; }
        public int id_direccion { get; set; }
        public string titulo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public byte[] foto { get; set; }
        public int idUsuario { get; set; }
        public string usuario { get; set; }
    }
}
